MVCLibrary/Controllers/BookController.cs
using MVCLibrary.Abstract.IServices;
using MVCLibrary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLibrary.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;

        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }

        // GET: Book
        public ActionResult Index(Cart cart)
        {
            return View(_bookService.GetBookViewModel(cart));
        }

        public ActionResult Search()
        {
            return View();
        }



    }
}

MVCLibrary/Controllers/LendController.cs
using MVCLibrary.Abstract.IRepository;
using MVCLibrary.IRepository;
using MVCLibrary.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLibrary.Controllers
{
    public class LendController : Controller
    {
        private readonly ILendRepository _lendRepository;
        private readonly IBookRepository _bookRepository;
        private readonly IUserRepository _userRepository;

        public LendController(ILendRepository lendRepository, IBookRepository bookRepository, IUserRepository userRepository)
        {
            _lendRepository = lendRepository;
            _bookRepository = bookRepository;
            _userRepository = userRepository;
        }



        // GET: Lend
        public ActionResult Index()
        {
            var lends = _lendRepository.GetALLLends();
            var lendViewModels = new List<LendViewModel>();
            foreach (var item in lends)
            {
                var book = _bookRepository.GetBookById(item.IdBook);
                var user = _userRepository.GetUserById(item.IdUser);
                lendViewModels.Add(
                    new LendViewModel
                    {
                        Author=book.Author,
                        Title=book.Title,
                        ISBN=book.ISBN,
                        State=item.State,
                        DateBorrowed=item.DateBorrowed,
                        DateReturn=item.DateReturn,
                        Name=user.Name,
                        Surname=user.Surname,
                        Id=item.Id
                    });
            }
            return View(lendViewModels);
        }
    }
}

MVCLibrary/Views/Shared/_LanguagePartial.cshtml
    <li>@Html.ActionLink("Polish", "Change", "Language", new { Language = "pl" }, null)</li>
    <li>@Html.ActionLink("English", "Change", "Language", new { Language="pl"},null)</li>

MVCLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MVC Library</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .libraryCart {
            background: url(../Images/shopingCart.png) no-repeat;
            background-size: 48px 48px;
            width: 48px;
            height: 48px;
            display: block;
            text-indent: -9999px;
        }
    </style>
</head>
<body ng-app="mvcLibrary">

    <div class="wrapper">
        <!-- Sidebar Holder -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>@Html.ActionLink(@MVCLibrary.Resources.HomeTexts.Library, "Index", "Home")</h3>
            </div>
            <ul class="list-unstyled components">


                @* KSIAZKI *@
                <li class="active">
                    <a href="#bookSubmenu" data-toggle="collapse" aria-expanded="false">@MVCLibrary.Resources.HomeTexts.Books</a>
                    <ul class="collapse list-unstyled" id="bookSubmenu">
                        <li><a href="#">Wyszukaj</a></li>
                        <li>@Html.ActionLink(@MVCLibrary.Resources.HomeTexts.Books, "Index", "Book")</li>
                        @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                        {
                            <li>@Html.ActionLink(@MVCLibrary.Resources.HomeTexts.AddNewBook, "AddBook", "Admin")</li>
                        }
                    </ul>
                </li>


                @* KATEGORIE *@

                <li>
                    <a href="#categorySubmenu" data-toggle="collapse" aria-expanded="false">@MVCLibrary.Resources.HomeTexts.BookCategories</a>
                    <ul class="collapse list-unstyled" id="categorySubmenu">
                        <li>@Html.ActionLink(@MVCLibrary.Resources.HomeTexts.BookCategories, "Index", "Category")</li>
                        @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                        {
                            <li>@Html.ActionLink(@MVCLibrary.Resources.HomeTexts.AddCategory, "AddCategory", "Admin")</li>
                        }
                        <li><a href="#">Page 3</a></li>
                    </ul>
                </li>


                @* CZYTELNICY *@
                @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Worker")))
                {
                    <li>
                        <a href="#clientsSubmenu" data-toggle="collapse" aria-expanded="false">Czytelnicy</a>
                        <ul class="collapse list-unstyled" id="clientsSubmenu">
                          <li> @Html.ActionLink("Spis klientów", "GetClients", "Admin")</li>
                            <li>@Html.ActionLink("Wypożyczenia", "Index", "Lend")</li>
                            <li><a href="#">Wyszukaj</a></li>
                        </ul>
                    </li>
                }
            </ul>
        </nav>

        <!-- Page Content Holder -->
        <div id="content" class="container col-lg-12">
            <nav class="navbar navbar-default">
                <div class="container-fluid">

                    <div class="navbar-header">
                        <button type="button" id="sidebarCollapse" class="navbar-btn">
                            <span></span>
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                    <!-- Zmiana jezyka-->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            @if (Request.Cookies["Language"] != null)
                            {
                                if (Request.Cookies["Language"].Value == "pl")
                                {
                                    <li>@Html.ActionLink("Angielski", "Change", "Language", new { Language = "en" }, null)</li>
                                }
                                else
                                {
                                    <li>@Html.ActionLink("Polish", "Change", "Language", new { Language = "pl" }, null)</li>
                                }
                            }
                            else
                            {
                                <li>@Html.ActionLink("Polish", "Change", "Language", new { Language = "pl" }, null)</li>
                            }
                        </ul>
                        <!-- Login PartialView-->
                        @Html.Partial("_LoginPartial")
                        <!-- Jakies podstrony-->
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#">Page</a></li>
                            <li><a href="#">Page</a></li>
                            <li><a href="#">Page</a></li>
                            <!-- Wozek do wypozyczenia -->
                            @if (Request.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Cart", "Index","Book", null, new { @class= "libraryCart" })</li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>

            <div class="container body-content">
                @RenderBody()
                <hr />

                <footer>
                    <p>&copy; @DateTime.Now.Year - MVC Library</p>
                </footer>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/controllers")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $(this).toggleClass('active');
            });
        });
    </script>
</body>
</html>